version: '3.8'
services:
  web:
    build: .
    container_name: django_project
    volumes:
      - .:/usr/src/app:rw
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    # tty: true  # Add this to keep the container interactive
